version: "3"
services:
  db:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: alunosUnipe
      MYSQL_USER: root
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
